# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn install -B --file pom.xml install
    - name: Compile with Maven
      run: mvn compile
    - name: Save public folder
      uses: actions/upload-artifact@v2
      with:
        name: DeployAKS-1.0-SNAPSHOT
        path: target/DeployAKS-1.0-SNAPSHOT.war
        
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download files to publish
        uses: actions/download-artifact@v2
        with:
          name: DeployAKS-1.0-SNAPSHOT
          path: ${project.basedir}/releases/
